# Generated by Django 4.1.3 on 2022-11-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name_plural': 'Receitas'},
        ),
    ]
