# Generated by Django 4.1.3 on 2022-11-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
