# Generated by Django 4.1.3 on 2022-11-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_alter_receita_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, height_field='height', upload_to='fotos/%d/%m/%Y', width_field='width'),
        ),
    ]
