# Generated by Django 4.1.3 on 2022-11-16 02:34

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0012_alter_receita_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='fotos/%d/%m/%Y', variations={'thumb': (375, 350)}),
        ),
    ]
