# Generated by Django 4.1.3 on 2022-11-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0015_alter_receita_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='descricao',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
