# Generated by Django 4.1.3 on 2022-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0016_receita_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
