# Generated by Django 4.1.3 on 2022-12-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0018_categoria_alter_receita_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
